apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base

images:
  - name: auth-service-image
    newName: ghcr.io/morningblossom/auth-service/service
    newTag: latest

secretGenerator:
  - name: auth-service-secret
    envs:
      - secret.env