apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui

  template:
    metadata:
      labels:
        app: kafka-ui

    spec:
      containers:
        - name: kafka-ui
          image: docker.io/provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
              name: http

          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "stud-hub-kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health

            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health

            initialDelaySeconds: 60
            periodSeconds: 20
