apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-cicd-deployer
  namespace: kafka
rules:
  - apiGroups: [""]
    resources:
      - services
      - persistentvolumeclaims
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete